### ISSUE TITLE
Participant count for a group and get group participant

### ISSUE THREAD

**Issue by bitaashna** [whatsplay/whatsapp-play#395]
Participant count-This method will count the no of participants for the group name provided.
Get Group Participant-This method is used to get all the participants.
 I would like to contribute to this as a part of **GSSOC'21**
 Can u please assign this task to me. @rpotter12

**Comment by rpotter12** [comment]
Hi @bitaashna, this will be a good idea. You can add these things in information of group while showing the information of a group.

**Comment by rpotter12** [comment]
Hi @bitaashna, this will be a good idea. You can add these things in information of group while showing the information of a group.

**Comment by bitaashna** [comment]
can u please label the issue as gssoc'21.
