### ISSUE TITLE
Creating Group,Joining group,Setting Group Picture,Exiting Group

### ISSUE THREAD

**Issue by bitaashna** [whatsplay/whatsapp-play#397]
I would like to work on it as a part of GSSOC'21.
Can you please assign this work to me.

**Comment by rpotter12** [comment]
Hi @bitaashna, joining a group will not help this software. You can proceed with the other feature.

**Comment by Navya-amarneni** [comment]
I found this issue to be interesting.Can you assign this issue to me?
