### ISSUE TITLE
Need an update!

### ISSUE THREAD

**Issue by akashva50** [whatsplay/whatsapp-play#418]
**Bug Description**
Wplay stops by throwing some error after selecting the target for tracking.

**To Reproduce**
1. Go to 'Terminal'
2. Run wplay $python -m wplay -wt
3. select target chat
4. See error!

**Expected behaviour**
It should show target online status

**Screenshots**
![error](https://user-images.githubusercontent.com/35763811/112095657-e2ce0180-8bc2-11eb-9a7c-e1e444425db9.png)
You've selected the target named by: [--targetname--]
Waiting for selector "#app > div > div > div:nth-child(2) > div:last-of-type > span > div > span > div > div > div:first-child > div" failed: timeout 8000ms exceeds.
'NoneType' object is not subscriptable
Process Killed!
Traceback (most recent call last):
  File "/Users/aku/anaconda3/bin/wplay", line 5, in <module>
    from wplay.__main__ import main
  File "/Users/aku/anaconda3/lib/python3.8/site-packages/wplay/__main__.py", line 216, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/Users/aku/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/aku/anaconda3/lib/python3.8/site-packages/wplay/__main__.py", line 209, in main
    await get_and_match_args(parser)
  File "/Users/aku/anaconda3/lib/python3.8/site-packages/wplay/__main__.py", line 195, in get_and_match_args
    await target_info.target_info(args.target)
  File "/Users/aku/anaconda3/lib/python3.8/site-packages/wplay/target_info.py", line 103, in target_info
    await target_select.manual_select_target(page)
  File "/Users/aku/anaconda3/lib/python3.8/site-packages/wplay/utils/target_select.py", line 20, in manual_select_target
    target_search.__print_complete_target_info(complete_target_info)
  File "/Users/aku/anaconda3/lib/python3.8/site-packages/wplay/utils/target_search.py", line 431, in __print_complete_target_info
    for key in complete_target_info.keys():
AttributeError: 'NoneType' object has no attribute 'keys'

**Desktop information:**
 - OS: Mac Os Catalina 10.15.7
 - Browser: Chromium
 - Version :[71.0.3542.0 (Developer Build) (64-bit)]

**Comment by rpotter12** [comment]
@akashva50 Whatsapp change their whatsapp-web frontend code in some period of time. The selectors are changed. We need to edit the selector of this software. 

Please start fixing this error. :)

**Comment by akashva50** [comment]
Can u give a hint for editing selector cos i have no idea about doing that.

**Comment by akashva50** [comment]
> @akashva50 Whatsapp change their whatsapp-web frontend code in some period of time. The selectors are changed. We need to edit the selector of this software.
> 
> Please start fixing this error. :)

should i update "whatsapp_selectors_dict"?

**Comment by rpotter12** [comment]
> > @akashva50 Whatsapp change their whatsapp-web frontend code in some period of time. The selectors are changed. We need to edit the selector of this software.
> > Please start fixing this error. :)
> 
> should i update "whatsapp_selectors_dict"?

Yes. You only need add right selector

**Comment by akashva50** [comment]
> > > @akashva50 Whatsapp change their whatsapp-web frontend code in some period of time. The selectors are changed. We need to edit the selector of this software.
> > > Please start fixing this error. :)
> > 
> > 
> > should i update "whatsapp_selectors_dict"?
> 
> Yes. You only need add right selector

#app > div > div > div.Akuo4 > div._1Flk2._3xysY > span > div > span > div > div > section > div._3ZEdX._3hiFt.bRenh > div._1TFjN > span:nth-child(2)

how to edit above selector?

**Comment by rpotter12** [comment]
@akashva50 Open whatsapp-web. Check the valid selector there and change the whatsapp_selector according to that.
